code --install-extension alefragnani.project-manager
code --install-extension azemoh.one-monokai
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension florianloch.text-transform
code --install-extension flowtype.flow-for-vscode
code --install-extension johnpapa.vscode-peacock
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension karigari.chat
code --install-extension KnisterPeter.vscode-github
code --install-extension mohsen1.prettify-json
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode.atom-keybindings
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension PKief.material-icon-theme
code --install-extension Poorchop.theme-darktooth
code --install-extension QassimFarid.ejs-language-support
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension taniarascia.new-moon-vscode
code --install-extension Tyriar.sort-lines
code --install-extension xabikos.JavaScriptSnippets
code --install-extension zhuangtongfa.Material-theme
