code --install-extension alefragnani.project-manager
code --install-extension amlovey.shaderlabvscodefree
code --install-extension batisteo.vscode-django
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension dimasalmaz.unity3d-pack
code --install-extension donjayamanne.jupyter
code --install-extension donjayamanne.python-extension-pack
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension florianloch.text-transform
code --install-extension flowtype.flow-for-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.docker-explorer
code --install-extension jasonnutter.search-node-modules
code --install-extension jingkaizhao.vscode-redux-devtools
code --install-extension jorgeserrano.vscode-csharp-snippets
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension k--kato.docomment
code --install-extension kleber-swf.unity-code-snippets
code --install-extension lehni.vscode-titlebar-less-macos
code --install-extension leizongmin.node-module-intellisense
code --install-extension Leopotam.csharpfixformat
code --install-extension magicstack.MagicPython
code --install-extension mikestead.dotenv
code --install-extension mohsen1.prettify-json
code --install-extension ms-python.python
code --install-extension ms-vscode.atom-keybindings
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.node-debug2
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension PeterJausovec.vscode-docker
code --install-extension PKief.material-icon-theme
code --install-extension Poorchop.theme-darktooth
code --install-extension QassimFarid.ejs-language-support
code --install-extension robinbentley.sass-indented
code --install-extension sasa.vscode-sass-format
code --install-extension shinnn.stylelint
code --install-extension slevesque.shader
code --install-extension taniarascia.new-moon-vscode
code --install-extension tht13.python
code --install-extension Tobiah.unity-tools
code --install-extension Tyriar.sort-lines
code --install-extension Unity.unity-debug
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vsmobile.vscode-react-native
code --install-extension waderyan.nodejs-extension-pack
code --install-extension wholroyd.jinja
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xabikos.ReactSnippets
code --install-extension YclepticStudios.unity-snippets
