code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.project-manager
code --install-extension alexisvt.flutter-snippets
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension flowtype.flow-for-vscode
code --install-extension ms-vscode.atom-keybindings
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension paulhoughton.vscode-jscpd
code --install-extension PKief.material-icon-theme
code --install-extension Poorchop.theme-darktooth
code --install-extension sasa.vscode-sass-format
code --install-extension shinnn.stylelint
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension syler.sass-indented
code --install-extension taniarascia.new-moon-vscode
code --install-extension xabikos.JavaScriptSnippets
